### ISSUE TITLE
Some wrong links

### ISSUE THREAD

**Issue by rejurime** [SimonDarksideJ/XNAGameStudio#8]
Hi! Thanks for the work of keeping all these examples 😄.
While looking at the Shaders and Effects section, I noticed that 2 wiki pages have wrong links, I don't know how to collaborate with the wiki (sorry). I leave here how the links should be:

Wiki page: https://github.com/SimonDarksideJ/XNAGameStudio/wiki/Shader-Series-Coordinate-Spaces
Wrong link: https://github.com/SimonDarksideJ/XNAGameStudio/blob/master/Documents/CoordinateSpaces.docx?raw=true
The extension is doc not docx.
Link: https://github.com/SimonDarksideJ/XNAGameStudio/blob/master/Documents/CoordinateSpaces.doc?raw=true

Wiki page: https://github.com/SimonDarksideJ/XNAGameStudio/wiki/Generated-Geometry
Wrong link: https://github.com/DDReaper/XNAGameStudio/blob/master/Samples/XNA_GeneratedGeometry_01_small.jpg?raw=true
Wrong link: https://github.com/DDReaper/XNAGameStudio/blob/master/Samples/XNA_GeneratedGeometry_02_small.jpg?raw=true
Wrong folder, the files are in Images
Wrong link: https://github.com/DDReaper/XNAGameStudio/blob/master/Documents/GeneratedGeometrySample_4_0.zip?raw=true
Wrong folder, the file is in Samples

Links:
https://github.com/DDReaper/XNAGameStudio/blob/master/Images/XNA_GeneratedGeometry_01_small.jpg?raw=true
https://github.com/DDReaper/XNAGameStudio/blob/master/Images/XNA_GeneratedGeometry_02_small.jpg?raw=true
https://github.com/DDReaper/XNAGameStudio/blob/master/Samples/GeneratedGeometrySample_4_0.zip?raw=true

**Comment by SimonDarksideJ** [comment]
Only just spotted this @rejurime so thanks for the info. Will see about getting those updated

**Comment by SimonDarksideJ** [comment]
Darn, seems my github account rename has now really messed up the Wiki.  Time for a global search/replace :D

**Comment by SimonDarksideJ** [comment]
Actually turns out all the content needs a little love to meet the new GitHub standards :D 
SO working through and will fix this.
